#!/bin/bash
#chmod +x tmake 
rm ./toan_mpig
clear
echo building
#export PATH=$PATH:/usr/local/cuda-8.0/bin
mpic++ -g main.cpp MLSOMA.cpp MPIMessage.cpp MPITool.cpp MSOMA.cpp SerializedSharedMemory.cpp SOMA_Sequence.cpp Source.cpp TDefine.cpp TestFunctions.cpp TimeAnalysis.cpp TOutput.cpp TVector.cpp -o toan_mpig -Wno-deprecated-gpu-targets
#-gencode arch=compute_20,code=sm_20
#cuda-gdb ./toan_mpigg
#run
#where
./toan_mpig